<?php

/**
 * BaseShitsMeList
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property string $description
 * 
 * @method string      getTitle()       Returns the current record's "title" value
 * @method string      getDescription() Returns the current record's "description" value
 * @method ShitsMeList setTitle()       Sets the current record's "title" value
 * @method ShitsMeList setDescription() Sets the current record's "description" value
 * 
 * @package    edenapps
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseShitsMeList extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('shits_me_list');
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}