<?php

/**
 * BaseBox
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property clob $description
 * @property string $picture
 * 
 * @method string getTitle()       Returns the current record's "title" value
 * @method clob   getDescription() Returns the current record's "description" value
 * @method string getPicture()     Returns the current record's "picture" value
 * @method Box    setTitle()       Sets the current record's "title" value
 * @method Box    setDescription() Sets the current record's "description" value
 * @method Box    setPicture()     Sets the current record's "picture" value
 * 
 * @package    edenapps
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBox extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('box');
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('description', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('picture', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}