<?php

/**
 * BaseRoster
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $member_id
 * @property string $monday
 * @property string $tuesday
 * @property string $wednesday
 * @property string $thursday
 * @property string $friday
 * @property string $saturday
 * @property string $sunday
 * @property Members $Member
 * 
 * @method integer getMemberId()  Returns the current record's "member_id" value
 * @method string  getMonday()    Returns the current record's "monday" value
 * @method string  getTuesday()   Returns the current record's "tuesday" value
 * @method string  getWednesday() Returns the current record's "wednesday" value
 * @method string  getThursday()  Returns the current record's "thursday" value
 * @method string  getFriday()    Returns the current record's "friday" value
 * @method string  getSaturday()  Returns the current record's "saturday" value
 * @method string  getSunday()    Returns the current record's "sunday" value
 * @method Members getMember()    Returns the current record's "Member" value
 * @method Roster  setMemberId()  Sets the current record's "member_id" value
 * @method Roster  setMonday()    Sets the current record's "monday" value
 * @method Roster  setTuesday()   Sets the current record's "tuesday" value
 * @method Roster  setWednesday() Sets the current record's "wednesday" value
 * @method Roster  setThursday()  Sets the current record's "thursday" value
 * @method Roster  setFriday()    Sets the current record's "friday" value
 * @method Roster  setSaturday()  Sets the current record's "saturday" value
 * @method Roster  setSunday()    Sets the current record's "sunday" value
 * @method Roster  setMember()    Sets the current record's "Member" value
 * 
 * @package    edenapps
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRoster extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('roster');
        $this->hasColumn('member_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('monday', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('tuesday', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('wednesday', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('thursday', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('friday', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('saturday', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('sunday', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Members as Member', array(
             'local' => 'member_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}