generator:
  class: sfDoctrineGenerator
  param:
    model_class:           MenuItem
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          menu_item
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    
        display: [Name, Title, Parent]
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
