generator:
  class: sfDoctrineGenerator
  param:
    model_class:           MenuItem
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          menu_item
    with_doctrine_route:   true
    actions_base_class:    sfActions    
    
    config:
      actions:
        custom: 
          label: Custom action
          params: {method: post}
      fields:  ~
      list:
        title:   Food and Drinks
        display: [Name, Title, Parent]
      filter:  ~
      form:    ~
      edit:    ~
      new:     
        title:  New Food and Drinks Item
