<?php

/**
 * BoxTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BoxTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BoxTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Box');
    }
}