<?php

/**
 * MembersTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MembersTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MembersTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Members');
    }
}