<?php

/**
 * RosterTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RosterTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RosterTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Roster');
    }
}