<?php

/**
 * ShitsMeListTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ShitsMeListTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ShitsMeListTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ShitsMeList');
    }
}