all:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn: 'mysql:host=127.0.0.1;dbname=edenapps'
      username: root
      password: 
prod:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn: 'mysql:host=localhost;dbname=edenapps'
      username: root
      password: zohair/naqvi/symfony/mysql
