<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2010/12/04 13:49:45

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=edenapps',
  'username' => 'root',
  'password' => 'zohair/naqvi/symfony/mysql',
  'name' => 'doctrine',
)),);
